// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uvytrveisbngkslnipkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV2eXRydmVpc2JuZ2tzbG5pcGtiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjczNjksImV4cCI6MjA3MjM0MzM2OX0.bR0BH24bWLXPJu4Kr2qam7aJUXXju6jdM2QfxMElVCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});